### ISSUE TITLE
Requirements not found since last HA update

### ISSUE THREAD

**Issue by nclsrm** [d03n3rfr1tz3/hass-divoom#13]
Hello,
Many thanks for your work. I've been using the integration with my Divoom Ditoo for several months now without any problems.
Unfortunately, since the last Home Assistant update, the integration doesn't seem to work any more, the Divoom platform is no longer recognised.
Also, my configuration.yaml file is no longer valid, and I get this error message: "Platform error notify.divoom - Requirements for divoom not found: ['pybluez==0.22']".
I've tried deleting and reinstalling the integration but nothing changes, I'm still getting the same error messages.
Am I the only one affected?

**Comment by d03n3rfr1tz3** [comment]
oh right, I forgot to change the manifest.json here. it works on my end since months already by just removing the pybluez requirement.

reason is, that with older versions of home assistant (like 2 years ago) the bluetooth socket functionality, which is basically shipped with python, was only available after installing pybluez. this problem got fixed a while ago, but I forgot about the pybluez dependency. pybluez is literally too old (and one of its dependencies does not compile in the HA instance), but not needed by this integration.

**Comment by d03n3rfr1tz3** [comment]
should be fixed with the new manifest.json now. 151c647
let me know if its also working on your end.

**Comment by nclsrm** [comment]
Yes, everything works now.
Thank you for the quick response!
