### ISSUE TITLE
Allow brightness for clock mode

### ISSUE THREAD

**Issue by bahuma20** [d03n3rfr1tz3/hass-divoom#18]
Right now brightness is only supported for "light" mode but not for "clock" mode.

**Comment by d03n3rfr1tz3** [comment]
I had a closer look into the protocol as well as the app again and recognized, that the brightness setting, which seems to be tied to the clock channel, actually is not sent in the same command. therefore the clock mode is correct as it is and does not allow additional parameters (spoiler: but one existing parameter can be improved).

the general brightness can be changed with a separate command and its very likely that the app is actually sending this command. that command and a few others will be added in the near future (hopefully this week). I also plan on improving the clock mode, because currently the clock style is hardcoded.
