### ISSUE TITLE
Pictures do not work properly 

### ISSUE THREAD

**Issue by urbanmc89** [d03n3rfr1tz3/hass-divoom#19]
I have tried several GIFs from the original Divoom app but also from the internet. 
None of them work properly. 
The gifs from the Divoom app only show the background color. With other gifs the service does not work at all. 
Format is 16x16.

**Comment by d03n3rfr1tz3** [comment]
Yes, not every GIF works out of the box. That's because GIFs are not all the same and especially not exactly the way the Pixoo (and other devices) want it to be.

The GIFs from the Divoom app for example are not 16x16 when downloaded. They are typically coming in the size 320x320, which is why you only see the background color.

You need to make sure the GIF is actually only 16x16 pixels, non-interlaced and with a global color palette. I can recommend resizing and converting it with GIMP (dont forget to set the checkbox for animation when exporting), as thats what I'm still doing and it still works perfectly.

## Example
Directly downloaded from the Divoom app without any change:
![3dprinter-source](https://github.com/d03n3rfr1tz3/hass-divoom/assets/1483070/9857a0db-07b3-403d-a2b2-711b442dba07)

Resized to 16x16 (no interpolation) and exported (animation yes, but no interlace) with GIMP:
![3dprinter-target](https://github.com/d03n3rfr1tz3/hass-divoom/assets/1483070/e061c295-e9e8-4493-8640-3add358b02af)
