### ISSUE TITLE
Confused by the Usage

### ISSUE THREAD

**Issue by Svision** [d03n3rfr1tz3/hass-divoom#2]
I am new to hass, and I am confused by the usage since I did not see where I can send those message 
`{
  "message": "",
  "data": {
    "mode": "MODE"
  }
}`
Could you be more specific?
Thank you!

**Comment by Svision** [comment]
Also, I did not find divoom under Developer Tools/Services

**Comment by d03n3rfr1tz3** [comment]
Tbh, I can't remember, why I documented that example in JSON format, but you can find copy&paste ready examples in the linked example file.
https://github.com/d03n3rfr1tz3/hass-divoom/blob/main/devices/pixoo.txt

As you already found out, you have to go to Developer Tools/Services and choose the service "divoom_pixoo". Of course you can do the same in an automation or script, but for testing you can use the Developer Tools first. If "divoom_pixoo" cannot be found in the Services, it is not configured or there was an error on startup. Check your HASS Logs and you probably will find an error and hopefully it is helpful enough to resolve the issue.

If the service is there, you can configure it using the UI mode or YAML mode. In the UI mode, it is enough to fill out the data part, but because the message is required, you should fill it with a space or something like that.
![grafik](https://user-images.githubusercontent.com/1483070/151658085-fa078b40-20c5-48f3-b7ac-9a3ad887e0b0.png)

In the YAML mode, you can copy the examples from above into the data-part of the service. It should look like this.
![grafik](https://user-images.githubusercontent.com/1483070/151658110-40e7f945-edb2-4c5e-bd0c-3d3c920d8f45.png)

And thats it. Hitting the "Run the Service" button should lead to something visible on your Pixoo, if everything is configured correctly. After that, the harder part comes: creating a lot of automations for everything that comes to your mind 😃

**Comment by Svision** [comment]
Thank you so much for the detailed explanation! I really appreciate it! Hope you have a great day!

**Comment by Svision** [comment]
Also, do you by any chance know how to pair pixoo in the home assistant OS? I could not find the place to type the command `sudo rfcomm connect hci0 my:ma:c_:ad:dr:es`

**Comment by d03n3rfr1tz3** [comment]
I'm not sure how its done with the HA OS, but on the supervisor installation you basically just connect via SSH and then you can configure the bluetooth interface and also connect, which only needs to be done manually once for pairing and testing. Maybe there is also a way to connect via SSH or a terminal and use the commands stated in the readme and hopefully they work the same way.

**Comment by Svision** [comment]
Thank you so much!
