### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by klawiszowy** [d03n3rfr1tz3/hass-divoom#24]
Hi!

I can't connect with my Pixoo MAX.

Error:
Rejestrator: homeassistant.config_entries
Źródło: config_entries.py:2444
Pierwsze zdarzenie: 15:46:07 (3 zdarzenia)
Ostatnio zalogowany: 15:46:44

Error occurred loading flow for integration divoom: No module named 'custom_components.divoom.config_flow'

**Comment by d03n3rfr1tz3** [comment]
if that's the only log entry you have, then you don't have a connection error. this entry is there, because the configuration UI is not implemented (yet). It does not stop the component from working. I also have it in my logs and it perfectly works with two divoom devices (even simultanously).

pair your divoom device (there are multiple ways to achieve that) and then you just call the corresponding service in HA to send commands

**Comment by d03n3rfr1tz3** [comment]
the error you mentioned should be gone with the latest version now. it also enables auto-discovery and UI configuration, which should make it easier to setup, if not already done through the configuration.yaml
