### ISSUE TITLE
Supported devices? How about AuraBox?

### ISSUE THREAD

**Issue by denilsonsa** [d03n3rfr1tz3/hass-divoom#34]
Hello! Is there a list of known supported devices somewhere? I expected to find such list on the README, but at most I found some example configuration on the [devices](https://github.com/d03n3rfr1tz3/hass-divoom/tree/main/custom_components/divoom/devices) directory.

I ask about it because I'm wondering if [AuraBox](http://download.divoom.com/download-aurabox.html) is supported. I guess this one is an older generation with less-capable graphics and [possibly a different protocol](https://github.com/derHeinz/divoom-adapter). But I don't have this device (in fact, I have no Divoom devices so far), so I can't test.

**Comment by d03n3rfr1tz3** [comment]
I bet it works out of the box. If you configure it like a Timebox, which should be the closest fit, it might work with all supported commands.

The reason, why it's not in the list is quite simple: I personally own only two Divoom devices and all other supported devices are listed/implemented, because the information available were good enough and/or they were newer then my oldest and older then my newest Divoom device. As you can see in the GitHub repo you linked, the information available (6-7 years ago) were limited. The protocol looks exactly the same, just way less information. That's why I guess, that it works.

Would be very helpful, if you could go into your Divoom app and somehow show/list me the features this Aurabox generally supports... and if possbile also try every command via my HA integration and give me feedback, what works and what not. Obviously only the commands that your Aurabox support can work. For example, if it does not have games available through the app, it very likely won't work with the games commands. That way, we could work out possible differences to the Timebox (Evo) and make the Aurabox a supported device. 😊

**Comment by denilsonsa** [comment]
Well, I don't have a device yet, and I'm still unsure if I want to buy one (probably from used market). I know there is [one app specifically for AuraBox](https://play.google.com/store/apps/details?id=com.cheerchip.aurabox1), and that's yet another reason I thought it used a different protocol.

Anyway… Here's a suggestion: How about creating a table on the README file listing all known Divoom devices, with a column pointing to their example configuration, and another column about their compatibility (as in "known working", "untested but probably supported", "feature xyz not supported", "known not working" etc.). Maybe later I can sketch such table and send a PR.

**Comment by d03n3rfr1tz3** [comment]
I added Aurabox to the supported devices and just guessed, what might actually be supported. It seems similar to the Timebox Mini and should therefore have nearly the same features with the newest firmware. If I counted correctly, the screen size is 10x10.

A table might be useful, but also needs a lot of input from more people and would probably not be seen by most users, because the readme already is quite long. \
Also there is the problem with the firmware version. My Pixoo alone already had multiple different stages of supported modes. The games and some of the tools were definitly not supported initially. Therefore I'd just go the route of basically guessing more optimistic and only give a warning, if it's actually known to not work. Like the audio stuff on devices without audio-support or the keyboard modes (from the Ditoo) on devices without that Ditoo specific keyboard.

In the end it's on the user end to look, what the device actually should support. If the Divoom app does not allow a specific mode or feature, it's unlikely this integration somehow can make it work/appear. Syncing this into a table including firmware versions just seems like a time-waste to me.
