### ISSUE TITLE
Pixoomax on/off

### ISSUE THREAD

**Issue by SeraphicRav** [d03n3rfr1tz3/hass-divoom#35]
Hi!

Thank you very much for this custom integration!

I have been able to pair my Pixoomax using Bluetooth. I have a succession of Gifs set by the Divoom app.

When I send an off message, I can see the screen turn off.

But the issue is when I send a message to turn it on, the succession of gifs us gone and instead there is a black screen with dark grey pixels slightly changing.

Is that the expected behavior? I was expecting to be able to see the original succession of gifs.

**Comment by d03n3rfr1tz3** [comment]
The on/off modes might be a bit misleading, yes. It basically switches to the light-channel, sets the given color and brightness and also sets the `power` flag. That flag is the only reason, why I even added these modes, besides the fact, that the separate brightness-mode wasn discovered at that time. Because the light-channel (as it also appears in the Divoom app) is just a separate view, there is no previous view that could be shown. You will still be in the light-channel, but because you probably did not specify a color, it is just black.

What you basically want is just turning down the brightness to 0, without changing anything else. Therefore I would recommend you to change your automation/script to send a brightness mode (with 0 or 100 as value) instead. That should do what you want.

The on-mode kinda needs an additional command to switch to the appreciated channel/tool after turning it on again.

**Comment by SeraphicRav** [comment]
Thank you very much! I managed to make it work.

I tried the brightness mode but it did not had any effect. 

Thanks to your explanation I understood the problem. To fix it in my case:
When I want to turn it off, just use mode off.
When I want to turn it on , call mode on then mode design number: 0 and I got what I wanted.
